#!/bin/bash

apt update
apt install apache2-utils

sed -n '/traefikpass/!p' .env

read -p "Введите пароль от traefik: " traefikp
traefikp=`htpasswd -nb admin $traefikp`

echo -en "traefikpass = $traefikp" >> .env  