defaultEntryPoints = ["http", "https"]

[entryPoints]
 [entryPoints.dashboard]
   address = ":8080"
   [entryPoints.dashboard.auth]
     [entryPoints.dashboard.auth.basic]
       users = ["$traefikpass"]
 [entryPoints.http]
   address = ":80"
     [entryPoints.http.redirect]
       entryPoint = "https"
 [entryPoints.https]
   address = ":443"
     [entryPoints.https.tls]

[api]
entrypoint="dashboard"

[acme]
 email = "$mail"
 storage = "acme.json"
 entryPoint = "https"
 onHostRule = true
   [acme.httpChallenge]
   entryPoint = "http"

[[acme.domains]]
  main = "$domain"
  sans = ["www.$domain", "vpnsec.$domain","monitor.$domain"]

[docker]
 domain = "$domain"
 watch = true
 network = "web"