defaultEntryPoints = ["http", "https"]

[entryPoints]
 [entryPoints.dashboard]
   address = ":8080"
   [entryPoints.dashboard.auth]
     [entryPoints.dashboard.auth.basic]
       users = ["admin:$apr1$phYCTqik$bslucAxXuCfLNVgtNnH3V/"]
 [entryPoints.http]
   address = ":80"
     [entryPoints.http.redirect]
       entryPoint = "https"
 [entryPoints.https]
   address = ":443"
     [entryPoints.https.tls]

[api]
entrypoint="dashboard"

[acme]
 email = "italky2@mail.ru"
 storage = "acme.json"
 entryPoint = "https"
 onHostRule = true
   [acme.httpChallenge]
   entryPoint = "http"

[[acme.domains]]
  main = "horsekfh.ru"
  sans = ["www.horsekfh.ru", "vpnsec.horsekfh.ru","monitor.horsekfh.ru"]   

[docker]
 domain = "horsekfh.ru"
 watch = true
 network = "web"
